<?php

namespace AppBundle\Repository;

use AppBundle\Entity\BlogPost;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param BlogPost $post
     * @return bool
     */
    public function addViewToPost(BlogPost $post)
    {
        $post->addView();
        $em = $this->getEntityManager();
        $em->persist($post);
        $em->flush();

        return true;
    }
}
